countries:
  england:
    name: England
    color: red
    regions:
      - name: Dublin
        x: 10
        y: 80
        text-x: 30
        text-y: 100
        cx: 60
        cy: 130
      - name: Edinburgh
        x: 160
        y: 80
        text-x: 180
        text-y: 100
        cx: 260
        cy: 105
      - name: Liverpool
        x: 120
        y: 130
        text-x: 140
        text-y: 150
        cx: 120
        cy: 155
      - name: Sheffield
        x: 220
        y: 130
        text-x: 240
        text-y: 150
        cx: 320
        cy: 155
      - name: London
        x: 160
        y: 180
        text-x: 180
        text-y: 200
        cx: 210
        cy: 230
  france:
    name: France
    color: blue
    regions:
      - name: Brest
        x: 150
        y: 275
        text-x: 170
        text-y: 295
        cx: 180
        cy: 275
      - name: Paris
        x: 250
        y: 260
        text-x: 270
        text-y: 280
        height: 30
      - name: Dijon
        x: 250
        y: 290
        text-x: 270
        text-y: 310
        height: 70
      - name: Bordeaux
        x: 150
        y: 325
        text-x: 170
        text-y: 345
        cx: 150
        cy: 350
        height: 85
      - name: Marseille
        x: 250
        y: 360
        text-x: 270
        text-y: 380
  germany:
    name: Germany
    color: black
    regions:
      - name: Hamburg
        x: 420
        y: 210
        text-x: 440
        text-y: 230
      - name: Berlin
        x: 520
        y: 210
        text-x: 540
        text-y: 230
        height: 125
      - name: Danzig
        x: 620
        y: 210
        text-x: 640
        text-y: 230
        height: 125
      - name: Cologne
        x: 390
        y: 260
        text-x: 410
        text-y: 280
        width: 130
      - name: Munich
        x: 350
        y: 310
        text-x: 370
        text-y: 330
        width: 170
  russia:
    name: Russia
    color: purple
    regions:
      - name: St. Petersburg
        x: 720
        y: 0
        text-x: 740
        text-y: 20
        height: 230
      - name: Moscow
        x: 820
        y: 0
        text-x: 840
        text-y: 20
        height: 270
        width: 205
      - name: Warsaw
        x: 720
        y: 230
        text-x: 740
        text-y: 250
        height: 105
      - name: Kiev
        x: 820
        y: 270
        text-x: 840
        text-y: 290
        height: 65
        width: 205
      - name: Odessa
        x: 860
        y: 335
        text-x: 880
        text-y: 355
        height: 150
        width: 165
  austria_hungary:
    name: Austria-Hungary
    color: yellow
    font-color: black
    regions:
      - name: Prague
        x: 520
        y: 335
        text-x: 540
        text-y: 355
        height: 50
        width: 240
      - name: Lemberg
        x: 760
        y: 335
        text-x: 780
        text-y: 355
        height: 50
        width: 85
      - name: Vienna
        x: 420
        y: 360
        text-x: 440
        text-y: 380
        height: 50
        width: 100
      - name: Budapest
        x: 520
        y: 385
        text-x: 540
        text-y: 405
        height: 100
        width: 325
      - name: Trieste
        x: 460
        y: 410
        text-x: 480
        text-y: 430
        height: 100
        width: 60
  italy:
    name: Italy
    color: green
    regions:
      - name: Genoa
        x: 320
        y: 410
        text-x: 340
        text-y: 430
        height: 65
        width: 80
      - name: Venice
        x: 400
        y: 410
        text-x: 420
        text-y: 430
        height: 115
        width: 60
      - name: Florence
        x: 340
        y: 475
        text-x: 360
        text-y: 495
        height: 50
        width: 60
      - name: Rome
        x: 360
        y: 525
        text-x: 380
        text-y: 545
        height: 60
        width: 80
      - name: Naples
        x: 380
        y: 585
        text-x: 400
        text-y: 605
        height: 100
        width: 60
neutrals:
  - name: Spain
    x: 100
    y: 410
    text-x: 120
    text-y: 430
    height: 150
    width: 200
  - name: Portugal
    x: 40
    y: 450
    text-x: 60
    text-y: 470
    height: 110
    width: 60
  - name: Morocco
    x: 0
    y: 750
    text-x: 20
    text-y: 770
    height: 60
    width: 225
  - name: Algeria
    x: 225
    y: 750
    text-x: 245
    text-y: 770
    height: 60
    width: 150
  - name: Tunisia
    x: 375
    y: 750
    text-x: 395
    text-y: 770
    height: 60
    width: 80
  - name: Belgium
    x: 350
    y: 250
    text-x: 355
    text-y: 270
    height: 70
    width: 40
  - name: Holland
    x: 390
    y: 225
    text-x: 400
    text-y: 245
    height: 35
    width: 30
  - name: Denmark
    x: 380
    y: 585
    text-x: 400
    text-y: 605
    height: 100
    width: 60
  - name: Norway
    x: 380
    y: 585
    text-x: 400
    text-y: 605
    height: 100
    width: 60
  - name: Sweden
    x: 380
    y: 585
    text-x: 400
    text-y: 605
    height: 100
    width: 60
  - name: West Balkan
    x: 380
    y: 585
    text-x: 400
    text-y: 605
    height: 100
    width: 60
  - name: Greece
    x: 380
    y: 585
    text-x: 400
    text-y: 605
    height: 100
    width: 60
  - name: Romania
    x: 380
    y: 585
    text-x: 400
    text-y: 605
    height: 100
    width: 60
  - name: Bulgaria
    x: 380
    y: 585
    text-x: 400
    text-y: 605
    height: 100
    width: 60
  - name: Turkey
    x: 380
    y: 585
    text-x: 400
    text-y: 605
    height: 100
    width: 60
sea_regions:
  - name: Baltic Sea
    width: 100
    height: 200
    x: 450
    y: 0
    text-x: 470
    text-y: 20
  - name: North Sea
    width: 225
    height: 200
    x: 225
    y: 0
    text-x: 245
    text-y: 20
  - name: North Atlantic
    width: 225
    height: 200
    x: 0
    y: 0
    text-x: 20
    text-y: 20
  - name: Bay of Biscay
    width: 225
    height: 550
    x: 0
    y: 200
    text-x: 20
    text-y: 300
  - name: English Channel
    width: 225
    height: 75
    x: 100
    y: 200
    text-x: 120
    text-y: 250
  - name: Western Mediterranean Sea
    width: 500
    height: 400
    x: 225
    y: 350
    text-x: 245
    text-y: 720
  - name: Ionian Sea
    width: 300
    height: 250
    x: 725
    y: 350
    text-x: 745
    text-y: 500
  - name: Black Sea
  - name: Eastern Mediterranean Sea
    width: 175
    height: 150
    x: 1025
    y: 450
    text-x: 1045
    text-y: 500
neighbors:
  Dublin: ["North Atlantic"]
  Edinburgh: ["North Sea", "Liverpool", "Sheffield"]
  Liverpool: ["North Atlantic", "Edinburgh", "Sheffield", "London"]
  Sheffield: ["Edinburgh", "Liverpool", "London", "North Sea"]
  London: ["Liverpool", "Sheffield", "English Channel"]
  Brest: ["English Channel", "Paris", "Bordeaux", "Dijon"]
  Paris: ["Brest", "Dijon", "Belgium"]
  Dijon: ["Munich", "Marseille", "Bordeaux", "Brest", "Paris", "Belgium"]
  Bordeaux: ["Bay of Biscay", "Brest", "Dijon", "Spain", "Marseille"]
  Marseille: ["Spain", "Bordeaux", "Dijon", "Genoa", "Western Mediterranean Sea"]
  Hamburg: ["Denmark", "North Sea", "Holland", "Berlin", "Cologne"]
  Berlin: ["Hamburg", "Cologne", "Munich", "Prague", "Danzig"]
  Danzig: ["Berlin", "Prague", "Baltic Sea", "Warsaw"]
  Cologne: []
  Munich: []
  St. Petersburg: []
  Moscow: []
  Warsaw: []
  Kiev: []
  Odessa: []
  Prague: []
  Lemberg: []
  Vienna: []
  Budapest: []
  Trieste: []
  Genoa: []
  Venice: []
  Florence: []
  Rome: []
  Naples: []
  Spain: ["Portugal", "Bordeaux", "Marseille"]
  Portugal: []
  Morocco: []
  Algeria: []
  Tunisia: []
  Belgium: []
  Holland: []
  Denmark: []
  Norway: []
  Sweden: []
  West Balkan: []
  Greece: []
  Romania: []
  Bulgaria: []
  Turkey: []
  Baltic Sea: []
  North Sea: []
  North Atlantic: []
  English Channel: []
  Bay of Biscay: []
  Western Mediterranean Sea: []
  Ionian Sea: []
  Black Sea: []
starting_factories:
  armaments: ["Paris", "Berlin", "Moscow", "Vienna", "Budapest", "Rome"]
  shipyards: ["Liverpool", "London", "Hamburg", "Bordeaux", "Naples", "Odessa"]
factories:
  armaments: ["Sheffield", "Cologne", "Munich", "Warsaw", "Kiev", "Lemberg", "Prague", "Dijon", "Florence", "Paris", "Berlin", "Moscow", "Vienna", "Budapest", "Rome"]
  shipyards: ["Edinburgh", "Dublin", "Danzig", "St. Petersburg", "Brest", "Marseille", "Genoa", "Venice", "Trieste", "Liverpool", "London", "Hamburg", "Bordeaux", "Naples", "Odessa"]

