countries:
  england:
    name: england
    color: red
    font_color: black
    regions:
      - name: dublin
      - name: edinburgh
      - name: liverpool
      - name: sheffield
      - name: london
  france:
    name: france
    color: blue
    font_color: white
    regions:
      - name: brest
      - name: paris
      - name: dijon
      - name: bordeaux
      - name: marseille
  germany:
    name: germany
    color: black
    font_color: white
    regions:
      - name: hamburg
      - name: berlin
      - name: danzig
      - name: cologne
      - name: munich
  russia:
    name: russia
    color: purple
    font_color: black
    regions:
      - name: st_petersburg
      - name: moscow
      - name: warsaw
      - name: kiev
      - name: odessa
  austria_hungary:
    name: austria_hungary
    color: '#CCCC00'
    font_color: black
    regions:
      - name: prague
      - name: lemberg
      - name: vienna
      - name: budapest
      - name: trieste
  italy:
    name: italy
    color: green
    font_color: black
    regions:
      - name: genoa
      - name: venice
      - name: florence
      - name: rome
      - name: naples
neutrals:
  - name: spain
  - name: portugal
  - name: morocco
  - name: algeria
  - name: tunisia
  - name: belgium
  - name: holland
  - name: denmark
  - name: norway
  - name: sweden
  - name: west_balkan
  - name: greece
  - name: romania
  - name: bulgaria
  - name: turkey
sea_regions:
  - name: baltic_sea
  - name: north_sea
  - name: north_atlantic
  - name: bay_of_biscay
  - name: english_channel
  - name: western_mediterranean_sea
  - name: ionian_sea
  - name: black_sea
  - name: eastern_mediterranean_sea
neighbors:
  dublin: ["north_atlantic"]
  edinburgh: ["north sea", "liverpool", "sheffield"]
  liverpool: ["north atlantic", "edinburgh", "sheffield", "london"]
  sheffield: ["edinburgh", "liverpool", "london", "north_sea"]
  london: ["liverpool", "sheffield", "english_channel"]
  brest: ["english_channel", "paris", "bordeaux", "dijon"]
  paris: ["brest", "dijon", "belgium"]
  dijon: ["munich", "marseille", "bordeaux", "brest", "paris", "belgium"]
  bordeaux: ["bay_of_biscay", "brest", "dijon", "spain", "marseille"]
  marseille: ["spain", "bordeaux", "dijon", "genoa", "western_ mediterranean_sea"]
  hamburg: ["denmark", "north_sea", "holland", "berlin", "cologne"]
  berlin: ["hamburg", "cologne", "munich", "prague", "danzig"]
  danzig: ["berlin", "prague", "baltic_sea", "warsaw"]
  cologne: ["hamburg", "berlin", "munich", "belgium", "holland"]
  munich: ["cologne", "prague", "vienna", "dijon", "belgium", "berlin"]
  st_petersburg: ["moscow", "warsaw", "danzig"]
  moscow: ["st_petersburg", "warsaw", "kiev"]
  warsaw: ["st_petersburg", "moscow", "kiev", "lemberg", "prague", "danzig"]
  kiev: ["moscow", "warsaw", "lemberg", "romania", "odessa"]
  odessa: ["kiev", "romania", "black_sea"]
  prague: ["danzig", "berlin", "munich", "vienna", "trieste", "budapest", "lemberg", "warsaw"]
  lemberg: ["warsaw", "kiev", "romania", "budapest", "prague"]
  vienna: ["munich", "venice", "budapest", "prague", "trieste", "genoa"]
  budapest: ["lemberg", "prague", "vienna", "romania", "trieste", "west_balkan"]
  trieste: ["vienna", "budapest", "west_balkan", "venice"]
  genoa: ["marseille", "vienna", "venice", "florence"]
  venice: ["genoa", "florence", "vienna", "trieste", "rome"]
  florence: ["genoa", "venice", "rome"]
  rome: ["florence", "venice", "naples"]
  naples: ["rome"]
  spain: ["portugal", "bordeaux", "marseille"]
  portugal: ["spain"]
  morocco: []
  algeria: []
  tunisia: []
  belgium: []
  holland: []
  denmark: []
  norway: []
  sweden: []
  west_balkan: []
  greece: []
  romania: []
  bulgaria: []
  turkey: []
  baltic_sea: []
  north_sea: []
  north_atlantic: []
  english_channel: []
  bay_of_biscay: []
  western_mediterranean_sea: []
  ionian_sea: []
  black_sea: []
starting_factories:
  armaments: ["paris", "berlin", "moscow", "vienna", "budapest", "rome"]
  shipyards: ["liverpool", "london", "hamburg", "bordeaux", "naples", "odessa"]
factories:
  armaments: ["sheffield", "cologne", "munich", "warsaw", "kiev", "lemberg", "prague", "dijon", "florence", "paris", "berlin", "moscow", "vienna", "budapest", "rome"]
  shipyards: ["edinburgh", "dublin", "danzig", "st_petersburg", "brest", "marseille", "genoa", "venice", "trieste", "liverpool", "london", "hamburg", "bordeaux", "naples", "odessa"]
tax_chart:
  ["2-5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15+"]
